### ISSUE TITLE
TypeError if number of .md5 files in carrier directory not equal to 1

### ISSUE THREAD

**Issue by bitsgalore** [KBNLresearch/omSipCreator#3]
If the number of .md5 files in a carrier directory is not equal to 1, this results in the following error:

```
Traceback (most recent call last):
  File "/home/johan/omSipCreator/omSipCreator/omsipcreator.py", line 829, in <module>
    main()
  File "/home/johan/omSipCreator/omSipCreator/omsipcreator.py", line 735, in main
    fileGrp, divDisc, fileCounter = processCarrier(thisCarrier, fileGrp, dirSIP, fileCounterStart)
TypeError: 'NoneType' object is not iterable
```

This happens because most of the carrier-level processing in the _ProcessCarrier_ is now skipped if _skipChecksumVerification_ is _False_. See here:

https://github.com/KBNLresearch/omSipCreator/blob/master/omSipCreator/omsipcreator.py#L190

Solution: reorganise _ProcessCarrier_ function and move as much code as possible out of conditional block.

**Comment by bitsgalore** [comment]
fixed by <https://github.com/KBNLresearch/omSipCreator/commit/35913cc7cbe225efda12654b7ac209972429698d>
